#!/usr/bin/env python3
"""Build VALIDATION_REPORT.md from answer JSONs + factcheck.

    python scripts/validation_report.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pipeline.config import ANSWERS_DIR, PDF_DIR, ROOT
from pipeline.factcheck import compare_pair, factcheck_file

STATES = ("answer", "not_applicable", "missing_information", "bank_reserved", "human_action")
OUT = ROOT / "VALIDATION_REPORT.md"


def main() -> None:
    paths = sorted(ANSWERS_DIR.glob("form_*.json"))
    if not paths:
        raise SystemExit(f"No answers in {ANSWERS_DIR}")

    lines: list[str] = [
        "# Validation report",
        "",
        "Generated by `python scripts/validation_report.py`.",
        "Every `answer` must cite a resolvable source pointer; traps and FR/EN parity are checked.",
        "",
        "## Per-form state counts",
        "",
        "| Form | Company | Fields | answer | not_applicable | missing | bank_reserved | human_action | elapsed_s | Factcheck |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]

    total: Counter = Counter()
    all_ok = True
    details: list[str] = []

    for path in paths:
        data = json.loads(path.read_text(encoding="utf-8"))
        form = data.get("exercice") or path.stem
        company = data.get("company") or "?"
        fields = data.get("fields") or []
        counts = Counter(a.get("state") for a in fields)
        total.update(counts)
        report = factcheck_file(path, fix=False)
        status = "OK" if report["ok"] else "ISSUES"
        if not report["ok"]:
            all_ok = False
        elapsed = data.get("elapsed_seconds")
        lines.append(
            f"| `{form}` | {company} | {len(fields)} | "
            f"{counts.get('answer', 0)} | {counts.get('not_applicable', 0)} | "
            f"{counts.get('missing_information', 0)} | {counts.get('bank_reserved', 0)} | "
            f"{counts.get('human_action', 0)} | {elapsed if elapsed is not None else '—'} | {status} |"
        )
        if report["field_issues"] or report["trap_issues"]:
            details.append(f"### {form}")
            for label, issues in report["field_issues"][:20]:
                details.append(f"- `{label[:70]}`: {issues[0]}")
            for issue in report["trap_issues"]:
                details.append(f"- TRAP: {issue}")
            details.append("")

    lines += [
        "",
        f"**Total fields:** {sum(total.values())} · "
        + " · ".join(f"{s}={total.get(s, 0)}" for s in STATES),
        "",
        "## Cross-locale check (same company)",
        "",
    ]
    pair = compare_pair(ANSWERS_DIR / "form_02.json", ANSWERS_DIR / "form_04.json")
    if pair:
        all_ok = False
        lines.append("**form_02 vs form_04:** ISSUES")
        for issue in pair:
            lines.append(f"- {issue}")
    else:
        lines.append("**form_02 vs form_04:** OK — concept-level agreement (Belorive FR/EN).")

    lines += ["", "## Filled PDFs", ""]
    for form in [p.stem for p in paths]:
        candidates = [
            PDF_DIR / f"{form}_completed.pdf",
            PDF_DIR / f"{form}.filled.pdf",
            ROOT / "output" / f"{form}_completed.pdf",
            ROOT / "output" / "pdfs" / f"{form}.filled.pdf",
        ]
        pdf = next((p for p in candidates if p.exists()), candidates[0])
        lines.append(f"- `{'OK' if pdf.exists() else 'MISSING'}` — `{pdf.relative_to(ROOT)}`")

    lines += [
        "",
        "## Method guardrails",
        "",
        "- LLM maps labels → concepts / candidate pointers only (never writes values).",
        "- Code resolves values from the tagged fact store (`document#/json_pointer`).",
        "- Admissible roles: `primaire`, `fiche sujet`, `dérivé` (copies are not independent proof).",
        "- Reporting scope: client + controlled descendants (upstream parent excluded).",
        "- Signatures → `human_action`; bank boxes → `bank_reserved`.",
        "- Parent tax residence is not inferred from incorporation when the pack says it is missing.",
        "",
        f"## Verdict",
        "",
        f"**{'READY' if all_ok else 'NOT READY'}** — factcheck {'passed' if all_ok else 'failed'} on all forms.",
        "",
    ]
    if details:
        lines += ["## Issues detail", ""] + details

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({'OK' if all_ok else 'ISSUES'})")
    raise SystemExit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
